#Login as jci@pdx.edu
mutation loginMutation($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    fname
    lname
    email
  }
}
#variables
{
  "email":"jci@pdx.edu",
  "password": "password"
}
mutation createUserMutation($userInput: CreateUserInput!){
  createUser(input: $userInput) {
    user {
      id
      fname
    }
  }
}
  "userInput": {
    "email":"jakobinwins@gmail.com",
    "password": "password",
    "fname":"Jake",
    "lname":"Irwin",
    "passwordConfirmation":"password",
    "dpsst":"75323",
  }
}